#!/usr/bin/env bash
# Auto-detect AMD GPU arch, configure env vars, install deps.
# Usage:  ./setup.sh            # interactive
#         ./setup.sh --yes      # accept all defaults

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# ------------------------------------------------------------------------------
# 1. Detect GPU
# ------------------------------------------------------------------------------
if ! command -v rocm-smi >/dev/null 2>&1; then
    echo "[setup] ERROR: rocm-smi not found. Install ROCm 7.1+ first."
    echo "        See https://rocm.docs.amd.com/en/latest/deploy/linux/quick_start.html"
    exit 1
fi

GFX="$(rocm-smi --showhw 2>/dev/null | awk '/GFX/ {print $NF; exit}')"
if [ -z "$GFX" ]; then
    # Fallback: try from /opt/rocm/bin/rocminfo
    GFX="$(rocminfo 2>/dev/null | awk '/^ *Name:/ {print $2; exit}' | grep -o 'gfx[0-9]*')"
fi

if [ -z "$GFX" ]; then
    echo "[setup] WARN: could not detect GPU arch automatically. Defaulting to gfx1101."
    GFX="gfx1101"
fi
echo "[setup] Detected GPU arch: $GFX"

# Map arch to HSA_OVERRIDE_GFX_VERSION (what ROCm runtime expects)
case "$GFX" in
  gfx1100) HSA_OV="11.0.0" ;;
  gfx1101) HSA_OV="11.0.1" ;;
  gfx1102) HSA_OV="11.0.2" ;;
  gfx1030) HSA_OV="10.3.0" ;;
  gfx942)  HSA_OV="9.4.2"  ;;
  *)       HSA_OV="${GFX#gfx}"; HSA_OV="${HSA_OV:0:1}.${HSA_OV:1:1}.${HSA_OV:2:1}" ;;
esac

# ------------------------------------------------------------------------------
# 2. Write env file
# ------------------------------------------------------------------------------
cat > "$SCRIPT_DIR/.env.rocm" <<EOF
# Auto-generated by flux-amd-rocm/setup.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# source this file before running generate.py or bench.py:
#   source .env.rocm

export HSA_OVERRIDE_GFX_VERSION=$HSA_OV
export PYTORCH_ROCM_ARCH=$GFX
export PYTORCH_ALLOC_CONF=expandable_segments:True
export TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1
export TOKENIZERS_PARALLELISM=false
export HF_HUB_DISABLE_TELEMETRY=1

# Single GPU by default. Set HIP_VISIBLE_DEVICES=0,1,2,... for multi-GPU.
export HIP_VISIBLE_DEVICES=\${HIP_VISIBLE_DEVICES:-0}

# Optional but recommended on RDNA3 (hipBLASLt tuned GEMM backend)
export TORCH_BLAS_PREFER_HIPBLASLT=1

# Persistent Triton kernel cache (huge speedup on re-runs)
export TORCHINDUCTOR_CACHE_DIR=\${TORCHINDUCTOR_CACHE_DIR:-$SCRIPT_DIR/.cache/torchinductor}
mkdir -p "\$TORCHINDUCTOR_CACHE_DIR"
EOF

echo "[setup] Wrote env file: $SCRIPT_DIR/.env.rocm"
echo "        - HSA_OVERRIDE_GFX_VERSION=$HSA_OV"
echo "        - PYTORCH_ROCM_ARCH=$GFX"

# ------------------------------------------------------------------------------
# 3. Install Python deps
# ------------------------------------------------------------------------------
YES=0
if [ "${1:-}" = "--yes" ]; then YES=1; fi

if [ -z "$VIRTUAL_ENV" ] && [ "$YES" = "0" ]; then
    echo ""
    echo "[setup] You are not in a virtualenv. Proceeding will install packages system-wide."
    read -rp "        Continue? [y/N] " ans
    [ "$ans" = "y" ] || { echo "[setup] Aborted. Run: python -m venv venv && source venv/bin/activate && ./setup.sh"; exit 0; }
fi

echo "[setup] Installing Python deps from requirements.txt ..."
pip install -r requirements.txt

# ------------------------------------------------------------------------------
# 4. Done
# ------------------------------------------------------------------------------
cat <<EOF

[setup] ✓ done.

Next steps:
  1. Accept FLUX.1-dev license:  https://huggingface.co/black-forest-labs/FLUX.1-dev
  2. Export your HF token:       export HF_TOKEN=hf_xxxxxxxx
  3. Source the env file:        source .env.rocm
  4. Run:                        python generate.py "your prompt"

For multi-GPU or more control, see docs/adapt_your_gpu.md.
EOF
